name: Grid4D
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - argparse==1.4.0
      - attrs==23.2.0
      - backcall==0.2.0
      - cachetools==5.3.3
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.1.4
      - configargparse==1.7
      - cycler==0.11.0
      - dash==2.15.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dearpygui==1.10.1
      - decorator==5.1.1
      - fastjsonschema==2.19.1
      - flask==2.2.5
      - fonttools==4.38.0
      - fvcore==0.1.5.post20221221
      - grpcio==1.62.1
      - idna==3.6
      - imageio==2.31.2
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - ipython==7.34.0
      - ipywidgets==8.1.2
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.17.3
      - jupyter-core==4.12.0
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lpips==0.1.4
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mmcv==1.6.0
      - nbformat==5.7.0
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - ninja==1.11.1.1
      - numpy==1.21.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - open3d==0.17.0
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pandas==1.3.5
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - piq==0.8.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - plotly==5.18.0
      - plyfile==0.9
      - portalocker==2.7.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygments==2.17.2
      - pyhocon==0.3.60
      - pymcubes==0.1.4
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.9.0.post0
      - pytorch-msssim==1.0.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.4.0
      - retrying==1.3.4
      - rsa==4.9
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - six==1.16.0
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.66.2
      - traitlets==5.9.0
      - trimesh==4.3.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - wcwidth==0.2.13
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.10
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.15.0
prefix: /root/anaconda3/envs/Grid4D
